### ISSUE TITLE
[BUG]WorkPro:正常运行中的bot，有时会报No connection established. Last error: connect ECONNREFUSED。token does not exist

### ISSUE THREAD

**Issue by zhujunde** [wechaty/puppet-supports#467]
uncaught exception GError: 1 CANCELLED: Call cancelled
    at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:82:17)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:611:51)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /app/node_modules/@grpc/grpc-js/src/resolving-call.ts:132:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/app/node_modules/@grpc/grpc-js/src/client.ts:594:42)
    at ServiceClientImpl.event (/app/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
    at GrpcManager.startStream (/app/node_modules/@juzi/wechaty-puppet-service/src/client/grpc-manager.ts:309:37)
    at GrpcManager.start (/app/node_modules/@juzi/wechaty-puppet-service/src/client/grpc-manager.ts:161:16)
    at async PuppetService.onStart (/app/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:162:5)
    at async PuppetService.start (/app/node_modules/state-switch/src/service-ctl/service-ctl.ts:89:9)
    at async PuppetService.start (/app/node_modules/@juzi/wechaty-puppet/src/mixins/service-mixin.ts:34:7)
    at async PuppetService.start (/app/node_modules/@juzi/wechaty-puppet/src/mixins/ready-mixin.ts:24:7)
    at async WechatyImpl.start (/app/node_modules/@juzi/wechaty/src/wechaty-mixins/puppet-mixin.ts:98:11)
    at async WechatyImpl.start (/app/node_modules/state-switch/src/service-ctl/service-ctl.ts:81:11) {
  code: 1,
  details: 'Call cancelled'
}
17:45:03 ERR PuppetService ding() rejection: Error: 14 UNAVAILABLE: No connection established. Last error: connect ECONNREFUSED ip:port (2024-05-30T17:44:56.486Z)
17:45:03 WARN ResolverWechaty updateResolution() address not found target wechaty://token-service-discovery-test.juzibot.com/puppet_workpro_47a625d7129e4a109220493783d25b34: token does not exist
17:45:49 WARN PuppetWatchdogAgent start() reset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_SCAN)","timeoutMilliseconds":60000}
uncaught exception GError: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_SCAN)","timeoutMilliseconds":60000}"
    at Watchdog.reset (/app/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:519:28)
    at Watchdog.emit (node:domain:488:12)
    at Timeout._onTimeout (/app/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"onGrpcStreamEvent(EVENT_TYPE_SCAN)","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/app/node_modules/@juzi/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:519:28)\n' +
    '    at Watchdog.emit (node:domain:488:12)\n' +
    '    at Timeout._onTimeout (/app/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at processTimers (node:internal/timers:514:7)'
}
17:46:03 ERR PuppetService ding() rejection: Error: 14 UNAVAILABLE: No connection established. Last error: connect ECONNREFUSED ip:port (2024-05-30T17:44:56.486Z)

**Comment by su-chang** [comment]
现在试试是否正常了？

**Comment by zhujunde** [comment]
平时都正常，偶尔会出现这样的情况，好像出现这个情况后，扫描登录二维码后就会有这样的提示
![99b972bd-f5c6-4609-83e6-37037b410058](https://github.com/wechaty/puppet-supports/assets/143337112/28bee0f7-d6b3-4497-87c5-3e36066fd620)
重启服务后又正常了
