### ISSUE TITLE
WXWork: 长时间持续出现no grpc manager

### ISSUE THREAD

**Issue by zhujunde** [wechaty/puppet-supports#522]
在今天10点至14点之间，日志报出了大量的以下错误
default - Error: no grpc manager
    at PuppetService.get grpcManager [as grpcManager] (/app/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:86:13)
    at PuppetService.ding (/app/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:412:10)
    at Timeout._onTimeout (/app/node_modules/@juzi/wechaty-puppet-service/src/client/puppet-service.ts:2802:12)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7) 2024-07-12T05:41:04.224Z
报错后，cpu利用率长时间被占满，14点10分左右服务自己恢复正常了

**Comment by su-chang** [comment]
最近还有这种情况么？
