### ISSUE TITLE
Paimon: I have buy a token(Paimon), but I cant run the example(java)

### ISSUE THREAD

**Issue by simonwzb** [wechaty/puppet-supports#90]
Please make sure you have read the [Wechaty Puppet Service](https://wechaty.js.org/docs/puppet-services/) from Wechaty Official Website before you continue writting this issue.

## Question
LOG:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.module.kotlin.KotlinModule.<init>(IZZZLcom/fasterxml/jackson/module/kotlin/SingletonSupport;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
	at io.github.wechaty.utils.JsonUtils.<clinit>(JsonUtils.kt:12)
	at io.github.wechaty.user.manager.PuppetManager$Companion.resolveInstance(PuppetManager.kt:23)
	at io.github.wechaty.Wechaty.initPuppet(Wechaty.kt:194)
	at io.github.wechaty.Wechaty.start(Wechaty.kt:51)
Code:
Wechaty bot = Wechaty.instance(token)
                .onScan((qrcode, statusScanStatus, data) -> System.out.println(QrcodeUtils.getQr(qrcode)))
                .onLogin(user -> System.out.println(user))
                .onMessage(message -> {
                    Room room = message.room();
                    String text = message.text();
                    if (StringUtils.equals(text, "#ding")) {
                        if (room != null) {
                            room.say("dong");
                        }
                    }
                }).start(true);

**Comment by simonwzb** [comment]
[main] INFO io.github.wechaty.user.manager.PuppetManager - PuppetManager resolveInstance({"name":"Wechaty","puppet":"io.github.wechaty.grpc.GrpcPuppet","puppetOptions":{"token":"puppet_paimon_47S1XLO2lCTMRYNCgztwoVqODDwcPZbc","name":"DEFAULT"}})
[main] INFO org.reflections.Reflections - Reflections took 148 ms to scan 6 urls, producing 161 keys and 1559 values 
[main] ERROR io.github.wechaty.grpc.GrpcPuppet - start() rejection:
io.grpc.StatusRuntimeException: UNAUTHENTICATED: {code:8,message:"A token(120.55.60.194:7777) must be prefixed with a 'puppet_' "}
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.github.wechaty.grpc.PuppetGrpc$PuppetBlockingStub.start(PuppetGrpc.java:2744)
	at io.github.wechaty.grpc.GrpcPuppet.start(GrpcPuppet.kt:78)
	at io.github.wechaty.Wechaty.start(Wechaty.kt:52)
	at io.github.wechaty.example.Main.main(Main.java:29)
[main] INFO io.github.wechaty.Wechaty - start Wechaty

**Comment by zpaimon** [comment]
Java can't support paimon.see https://github.com/wechaty/java-wechaty/issues/77

You can try ts ,python or go.

**Comment by huan** [comment]
This is possible by using a Wechaty Token Gateway.

Learn more from:

- https://github.com/wechaty/puppet-xp/issues/38
